# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: npm --prefix ClientApp/ install 
  displayName: 'npm install'

#- script: npm install --save-dev @angular/cli
#  displayName: 'install angular cli'

- script: npm --prefix ClientApp/ run build
  displayName: 'ng build'

pool:
  vmImage: vs2017-win2016

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: npm --prefix ClientApp/ install 
  displayName: 'npm install'

#- script: npm install --save-dev @angular/cli
#  displayName: 'install angular cli'

- script: npm --prefix ClientApp/ run build
  displayName: 'ng build'