# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:



- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: dotnet build --configuration Release
      displayName: 'dotnet build Release'

    - script: npm install .\ClientApp\
      displayName: 'npm install'

    - script: npm run build .\ClientApp\
      displayName: 'ng build'
