# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.2.0'
    - script: dotnet build --configuration Release
      displayName: 'dotnet build Release'

    - script: npm --prefix ClientApp/ install 
      displayName: 'npm install'

    - script: npm --prefix ClientApp/ run build
      displayName: 'ng build'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: dotnet build --configuration Release
      displayName: 'dotnet build Release'

    - script: npm --prefix ClientApp/ install 
      displayName: 'npm install'

    - script: npm --prefix ClientApp/ run build
      displayName: 'ng build'
